- platform: template
  sensors:
    harmony_activity:
      value_template: >
        {% if is_state("remote.harmonyhub", 'on') %}
          {{ states.remote.harmonyhub.attributes.current_activity }}
        {% else %}
          PowerOff
        {% endif %}
- platform: template
  sensors:
    denon_source:
      value_template: '{{ states.media_player.denon_avr_x4200w.attributes["source"] }}'
      friendly_name: 'Denon Source'