#####################################################################
#
#   WEATHER SENSORS
#
#####################################################################

- platform: darksky
  api_key: !secret darksky_api
  units: auto
  scan_interval: '00:30'
  forecast:
    - 1
  monitored_conditions:
    - summary
    - icon
    - temperature
    - temperature_high
    - temperature_low
    - apparent_temperature
    - apparent_temperature_high
    - apparent_temperature_low
    - dew_point
    - cloud_cover
    - humidity      
    - precip_type
    - precip_intensity
    - precip_intensity_max
    - precip_probability
    - nearest_storm_distance
    - visibility
    - ozone
    - pressure
    - wind_bearing
    - wind_speed
    - minutely_summary
    - hourly_summary
    - daily_summary

    
# Convert the Wind Direction from degrees to cardinal
- platform: template
  sensors:
    friendly_wind_direction:
      friendly_name: 'Wind Direction'
      value_template: >-
        {%if states.sensor.dark_sky_wind_bearing.state | float<=11 %}N
        {% elif states.sensor.dark_sky_wind_bearing.state | float>348 %}N
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=34 | float>11 %}NNE
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=56 | float>34 %}NE
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=79 | float>56 %}ENE
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=101 | float>79 %}E
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=124 | float>101 %}ESE
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=146 | float>124 %}SE
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=169 | float>146 %}SSE
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=191 | float>169 %}S
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=214 | float>191 %}SSW
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=236 | float>214 %}SW
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=259 | float>236 %}WSW
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=281 | float>259 %}W
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=304 | float>281 %}WNW
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=326 | float>304 %}NW
        {% elif states.sensor.dark_sky_wind_bearing.state | float<=348 | float>326 %}NNW
        {%- endif %}
      icon_template: >-
        mdi:compass-outline

- platform: template
  sensors:
    friendly_wind_direction_1:
      friendly_name: 'Wind Direction'
      value_template: >-
        {%if states.sensor.dark_sky_wind_bearing_1d.state | float<=11 %}N
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float>348 %}N
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=34 | float>11 %}NNE
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=56 | float>34 %}NE
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=79 | float>56 %}ENE
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=101 | float>79 %}E
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=124 | float>101 %}ESE
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=146 | float>124 %}SE
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=169 | float>146 %}SSE
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=191 | float>169 %}S
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=214 | float>191 %}SSW
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=236 | float>214 %}SW
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=259 | float>236 %}WSW
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=281 | float>259 %}W
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=304 | float>281 %}WNW
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=326 | float>304 %}NW
        {% elif states.sensor.dark_sky_wind_bearing_1d.state | float<=348 | float>326 %}NNW
        {%- endif %}
      icon_template: >-
        mdi:compass


- platform: template
  sensors:
    friendly_wind_force:
      friendly_name: 'Wind Force'
      value_template: >-
        {%if states.sensor.dark_sky_wind_speed.state | float<1 %}
          Calm
        {% elif states.sensor.dark_sky_wind_speed.state | float>=73 %}
          Huricane Force
        {% elif states.sensor.dark_sky_wind_speed.state | float>=1 | float<=3 %}
          Light Air
        {% elif states.sensor.dark_sky_wind_speed.state | float>=4 | float<=7 %}
          Light Breeze
        {% elif states.sensor.dark_sky_wind_speed.state | float>=8 | float<=12 %}
          Gentle Breeze
        {% elif states.sensor.dark_sky_wind_speed.state | float>=13 | float<=18 %}
          Moderate Breeze
        {% elif states.sensor.dark_sky_wind_speed.state | float>=19 | float<=24 %}
          Fresh Breeze
        {% elif states.sensor.dark_sky_wind_speed.state | float>=25 | float<=31 %}
          Strong Breeze
        {% elif states.sensor.dark_sky_wind_speed.state | float>=32 | float<=38 %}
          High Winds
        {% elif states.sensor.dark_sky_wind_speed.state | float>=39 | float<=46 %}
          Gales
        {% elif states.sensor.dark_sky_wind_speed.state | float>=47 | float<=54 %}
          Severe Gales
        {% elif states.sensor.dark_sky_wind_speed.state | float>=55 | float<=63 %}
          Storm Winds
        {% elif states.sensor.dark_sky_wind_speed.state | float>=64 | float<=72 %}
          Violent Storm
        {%- endif %}
      icon_template: >-
        mdi:weather-windy


- platform: template
  sensors:
    friendly_wind_force_1:
      friendly_name: 'Wind Force'
      value_template: >-
        {%if states.sensor.dark_sky_wind_speed_1d.state | float<1 %}
          Calm
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=73 %}
          Huricane Force
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=1 | float<=3 %}
          Light Air
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=4 | float<=7 %}
          Light Breeze
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=8 | float<=12 %}
          Gentle Breeze
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=13 | float<=18 %}
          Moderate Breeze
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=19 | float<=24 %}
          Fresh Breeze
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=25 | float<=31 %}
          Strong Breeze
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=32 | float<=38 %}
          High Winds
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=39 | float<=46 %}
          Gales
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=47 | float<=54 %}
          Severe Gales
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=55 | float<=63 %}
          Storm Winds
        {% elif states.sensor.dark_sky_wind_speed_1d.state | float>=64 | float<=72 %}
          Violent Storm
        {%- endif %}
      icon_template: >-
        mdi:weather-windy
        
- platform: template
  sensors:
    friendly_pressure_trend:
      friendly_name: "Barometer"
      value_template: >-
        {% if is_state('sensor.pws_pressure_trend', '+') %}
          Rising
        {% elif is_state('sensor.pws_pressure_trend', '-') %}
          Falling
        {% else %}
          Steady
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.pws_pressure_trend', '+') %}
          mdi:trending-up
        {% elif is_state('sensor.pws_pressure_trend', '-') %}
          mdi:trending-down
        {% else %}
          mdi:trending-neutral
        {% endif %}