#####################################################################
#
#   PRESENCE SENSORS
#
#####################################################################
- platform: bayesian
  prior: 0.5
  name: 'Mark Presence'
  probability_threshold: 0.9
  observations:
    - entity_id: 'device_tracker.life360_mark_davies'
      prob_given_true: 0.95
      prob_given_false: 0.05
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.galaxys9_2'
      prob_given_true: 0.8
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
- platform: bayesian
  prior: 0.5
  name: 'Mandy Presence'
  probability_threshold: 0.9
  observations:
    - entity_id: 'device_tracker.life360_mandy_davies'
      prob_given_true: 0.95
      prob_given_false: 0.05
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.iphone_3'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
# - platform: bayesian
  # prior: 0.5
  # name: 'Guests Presence'
  # probability_threshold: 0.9
  # observations:
    # - entity_id: 'device_tracker.life360_guests'
      # prob_given_true: 0.95
      # prob_given_false: 0.05
      # platform: 'state'
      # to_state: 'home'
    # - entity_id: 'device_tracker.marksiphone5'
      # prob_given_true: 0.8
      # prob_given_false: 0.2
      # platform: 'state'
      # to_state: 'home'
- platform: aarlo
  monitored_conditions:
  - motion