#####################################################################
#
#   CAMERA SENSORS
#
#####################################################################
- platform: aarlo
  monitored_conditions:
  - motion
  - sound