- platform: wake_on_lan
  name: Vizzini
  mac: !secret vizzini_mac
  host: !secret vizzini_host
  turn_off:
    service: shell_command.turn_off_vizzini
  
- platform: wake_on_lan
  name: Fireswamp
  mac: !secret fireswamp_mac
  host: !secret fireswamp_host
  turn_off:
    service: shell_command.turn_off_fireswamp
    
- platform: wake_on_lan
  name: lgtv
  mac: !secret lgtv_mac
  host: !secret lgtv_host
  turn_off:
    service: media_player.turn_off
    entity_id: media_player.living_room_tv
    
- platform: ecoplug
  scan_interval: 10

- platform: mfi
  host: !secret mfi_host
  username: !secret mfi_username
  password: !secret mfi_password
  ssl: true
  verify_ssl: false

- platform: aarlo
  siren: True
  all_sirens: True
  snapshot: True
  siren_volume: 1
  siren_duration: 10

- platform: template
  switches:
    guest_motion:
      value_template: "{{ is_state('automation.turn_on_guest_room_lights', 'on') }}"
      turn_on:
        service: automation.turn_on
        entity_id: 
          - automation.turn_on_guest_room_lights
          - automation.turn_on_guest_room_lights_during_the_day_if_blind_closed
      turn_off:
        service: automation.turn_off
        entity_id:
          - automation.turn_on_guest_room_lights
          - automation.turn_on_guest_room_lights_during_the_day_if_blind_closed
  
- platform: template
  switches:
    bedroom_automations:
      value_template: "{{ is_state('automation.turn_on_bedroom_lights', 'on') }}"
      turn_on:
        service: automation.turn_on
        entity_id: 
          - automation.turn_on_bedroom_lights
          - automation.turn_off_bedroom_lights
          - automation.turn_on_bathroom_lights_energize
          - automation.turn_on_bathroom_lights_relax
          - automation.turn_on_bathroom_lights_nighttime
          - automation.turn_off_bathroom_lights
          - automation.turn_on_bathroom_extractor
          - automation.turn_off_bathroom_extractor
      turn_off:
        service: automation.turn_off
        entity_id:
          - automation.turn_on_bedroom_lights
          - automation.turn_off_bedroom_lights
          - automation.turn_on_bathroom_lights_energize
          - automation.turn_on_bathroom_lights_relax
          - automation.turn_on_bathroom_lights_nighttime
          - automation.turn_off_bathroom_lights
          - automation.turn_on_bathroom_extractor
          - automation.turn_off_bathroom_extractor
      
- platform: template
  switches:
    ps3_console:
      value_template: "{{ is_state('input_boolean.ps3_switch', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.ps3_switch
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.ps3_switch
    xbox_console:
      value_template: "{{ is_state('input_boolean.xbox_switch', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.xbox_switch
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.xbox_switch
      
- platform: template
  switches:
    # ZONE 1 MEDIA SWITCH
    zone_1:
      value_template: "{{ is_state('media_player.denon_avr_x4200w', 'on') }}"
      turn_on:
        service: media_player.turn_on
        entity_id:  media_player.denon_avr_x4200w
      turn_off:
        service: media_player.turn_off
        entity_id:  media_player.denon_avr_x4200w
          
    # ZONE 2 MEDIA SWITCH
    zone_2:
      value_template: "{{ is_state('media_player.denon_avr_x4200w_zone_2', 'on') }}"
      turn_on:
        service: media_player.turn_on
        entity_id:  media_player.denon_avr_x4200w_zone_2
      turn_off:
        service: media_player.turn_off
        entity_id:  media_player.denon_avr_x4200w_zone_2
    
    # XBOX HARMONY ACTIVITY
    xbox_one:
      value_template: "{{ is_state_attr('remote.harmonyhub', 'current_activity', 'Play Xbox One') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'Play Xbox One'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'PowerOff'
    
    # PLAYSTATION HARMONY ACTIVITY
    playstation:
      value_template: "{{ is_state_attr('remote.harmonyhub', 'current_activity', 'Play PS3') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'Play PS3'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'PowerOff'
    
    # FIRETV HARMONY ACTIVITY
    amazonfiretv:
      value_template: "{{ is_state_attr('remote.harmonyhub', 'current_activity', 'Watch Fire TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'Watch Fire TV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'PowerOff'
    
    # NETFLIX HARMONY ACTIVITY
    netflix:
      value_template: "{{ is_state_attr('remote.harmonyhub', 'current_activity', 'Watch Netflix') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'Watch Netflix'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'PowerOff'
    
    # TV HARMONY ACTIVITY
    cable:
      value_template: "{{ is_state_attr('remote.harmonyhub', 'current_activity', 'Watch TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'Watch TV'
      turn_off:
        service: remote.turn_on
        data:
          entity_id: remote.harmonyhub
          activity: 'PowerOff'
    # AUDIO 1, USED FOR ECHO AND MUSIC ZONE 1
    audio_1:
      value_template: "{{ is_state_attr('media_player.denon_avr_x4200w', 'source', 'Echo') and is_state('switch.floating_outlet_switch', 'on') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.floating_outlet_switch
        - service: media_player.turn_on
          entity_id:  media_player.denon_avr_x4200w
        - service: media_player.select_source
          data:
            entity_id:  media_player.denon_avr_x4200w
            source: Echo
        - service: media_player.volume_set
          data:
            entity_id:  media_player.denon_avr_x4200w
            volume_level: 0.7
      turn_off:
        - service: switch.turn_off
          entity_id: switch.floating_outlet_switch
        - service: media_player.turn_off
          entity_id:  media_player.denon_avr_x4200w

    # AUDIO 2, USED FOR ECHO AND MUSIC ZONE 2
    audio_2:
      value_template: "{{ is_state_attr('media_player.denon_avr_x4200w_zone_2', 'source', 'Echo') and is_state('switch.floating_outlet_switch', 'on') }}"
      turn_on:
        - service: switch.turn_on
          entity_id: switch.floating_outlet_switch
        - service: media_player.turn_on
          entity_id:  media_player.denon_avr_x4200w_zone_2
        - service: media_player.select_source
          data:
            entity_id:  media_player.denon_avr_x4200w_zone_2
            source: Echo
        - service: media_player.volume_set
          data:
            entity_id:  media_player.denon_avr_x4200w_zone_2
            volume_level: 0.7
      turn_off:
        - service: switch.turn_off
          entity_id: switch.floating_outlet_switch
        - service: media_player.turn_off
          entity_id:  media_player.denon_avr_x4200w_zone_2
          
          
- platform: template
  switches:
    surround_speakers:
      turn_on:
        service: switch.turn_on
        entity_id:
          - switch.mfi_surround_sender
          - switch.mfi_surround_speaker_left
          - switch.mfi_surround_speaker_right
      turn_off:
        service: switch.turn_off
        entity_id:
          - switch.mfi_surround_sender
          - switch.mfi_surround_speaker_left
          - switch.mfi_surround_speaker_right